 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: base                                                        
     # Surfaces =   7
     # Strips   =  70
     # Vortices = 350

  Sref =  124.86       Cref =  4.2350       Bref =  34.320    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -0.05897     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00000     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.00040
  CZtot =  -0.00000     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.00000
  CDtot =   0.00000
  CDvis =   0.00000     CDind = 0.0000001
  CLff  =   0.00000     CDff  = 0.0000001    | Trefftz
  CYff  =   0.00000         e =    0.0000    | Plane  


 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.247231    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.609577
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.045212
 y  mom.  Cm |    Cma = -29.242979    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.420378

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  71.850571    CLr =   0.000000
 y  force CY |    CYp =  -0.039097    CYq =  -0.000000    CYr =   1.242737
 x' mom.  Cl'|    Clp =  -0.487152    Clq =   0.000000    Clr =   0.095460
 y  mom.  Cm |    Cmp =   0.000000    Cmq =-379.958527    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.047273    Cnq =   0.000000    Cnr =  -1.020538

 Neutral point  Xnp =  19.823826

 Clb Cnr / Clr Cnb  =   1.149798    (  > 1 if spirally stable )
